routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('marketplace');
});

Auth::routes();

Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->name('login.{provider}');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::group(['middleware' => 'auth'], function()
{
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('products/add', 'ProductController@create')->name('products.create');

    Route::resource('products', 'ProductController')
        ->names('products')
        ->except(['create']);
});

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Entity\Product;
use App\Http\Repositories\ProductRepository;
use App\Http\Requests\ProductCreateRequest;
use App\Http\Requests\ProductUpdateRequest;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Support\Facades\Auth;

class ProductController extends Controller
{
    private $productRepository;

    public function __construct()
    {
        $this->productRepository = app(ProductRepository::class);
    }

    public function index()
    {
        $products = Product::all()->sortByDesc('updated_at');

        return view('products.index', compact('products'));
    }

    public function create()
    {
        $product = new Product();

        return view('products.create', compact('product'));
    }

    public function store(ProductCreateRequest $request)
    {
        $data = $request->input();

        $data['user_id'] = Auth::id();

        $product = (new Product())->create($data);

        if ($product) {
            return redirect()
                ->route('products.index')
                ->with(['success' => 'Successfully created']);
        } else {
            return back()->withErrors(['msg' => 'Creation error'])->withInput();
        }
    }

    public function show($id)
    {
        $product = Product::find($id);

        try {
            $this->authorize('view', $product);
        } catch (AuthorizationException $e) {
            return back()
                ->withErrors(['msg' => 'You don\'t have permission to view this product'])
                ->withInput();
        }

        return view('products.show', compact('product'));
    }

    public function edit($id)
    {
        $product = $this->productRepository->getEdit($id);

        if (empty($product)) {
            abort(404);
        }

        try {
            $this->authorize('update', $product);
        } catch (AuthorizationException $e) {
            return back()
                ->withErrors(['msg' => 'You don\'t have permission to edit this product'])
                ->withInput();
        }

        return view('products.edit', compact('product'));
    }

    public function update(ProductUpdateRequest $request, $id)
    {
        $product = $this->productRepository->getEdit($id);

        if (empty($product)) {
            return back()
                ->withErrors(['msg' => "Product with id=[{$id}] not found"])
                ->withInput();
        }

        try {
            $this->authorize('update', $product);
        } catch (AuthorizationException $e) {
            return back()
                ->withErrors(['msg' => 'You don\'t have permission to update this product'])
                ->withInput();
        }

        $data = $request->input();

        $result = $product->update($data);

        if ($result) {
            return redirect()
                ->route('products.show', $product->id)
                ->with(['success' => 'Successfully updated']);
        } else {
            return back()
                ->withErrors(['msg' => 'Updated error'])
                ->withInput();
        }
    }

    public function destroy($id)
    {
        $product = $this->productRepository->getEdit($id);

        if (empty($product)) {
            return back()
                ->withErrors(['msg' => "Product with id=[{$id}] not found"])
                ->withInput();
        }

        try {
            $this->authorize('delete', $product);
        } catch (AuthorizationException $e) {
            return back()
                ->withErrors(['msg' => 'You don\'t have permission to delete this product'])
                ->withInput();
        }

        $result = Product::destroy($id);

        if ($result) {
            return redirect()
                ->route('products.index')
                ->with(['success' => "Product with id=$id deleted"]);
        } else {
            return back()
                ->withErrors(['msg' => 'Deleted error'])
                ->withInput();
        }
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('products.index') }}">Products list</a>
                        </li>
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/marketplace.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Marketplace</div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <form method="POST" action="{{ route('products.store') }}">
        @csrf
        <div class="container">

            @include('products.includes.result_messages')

            <div class="row justify-content-center">
                <div class="col-md-9">
                    @include('products.includes.item_create_main_col')
                </div>
                <div class="col-md-3">
                    @include('products.includes.item_create_add_col')
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <form method="POST" action="{{ route('products.update', $product->id) }}">
        @method('PATCH')
        @csrf
        <div class="container">

            @include('products.includes.result_messages')

            <div class="row justify-content-center">
                <div class="col-md-9">
                    @include('products.includes.item_edit_main_col')
                </div>
                <div class="col-md-3">
                    @include('products.includes.item_edit_add_col')
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/products/includes/item_create_add_col.blade.php
<div class="row justify-content-center">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>

resources/views/products/includes/item_create_main_col.blade.php
<div class="row justify-content-center">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title"><h4>Create new product</h4></div>
            </div>
            <div class="card-body">
                <div class="tab-content">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" name="name" value="{{ old('name') }}"
                               id="name"
                               class="form-control"
                               minlength="3"
                               required
                        >
                    </div>
                    <div class="form-group">
                        <label for="price">Price</label>
                        <input type="text" name="price" value="{{ old('price') }}"
                               id="price"
                               class="form-control"
                               required
                        >
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/products/includes/item_edit_add_col.blade.php
<div class="row justify-content-center">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>
<br>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div>ID: {{ $product->id }}</div>
                    <div>Author: {{ $product->author->name }}</div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label for="title">Created</label>
                        <input type="text" value="{{ $product->created_at }}" class="form-control" disabled>
                    </div>
                    <div class="form-group">
                        <label for="title">Updated</label>
                        <input type="text" value="{{ $product->updated_at }}" class="form-control" disabled>
                    </div>
                </div>
            </div>
        </div>
    </div>

resources/views/products/includes/item_edit_main_col.blade.php
<div class="row justify-content-center">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title"><h4>Update product</h4></div>
            </div>
            <div class="card-body">
                <div class="tab-content">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" name="name" value="{{ old('name', $product->name) }}"
                               id="name"
                               class="form-control"
                               minlength="3"
                               required
                        >
                    </div>
                    <div class="form-group">
                        <label for="price">Price</label>
                        <input type="text" name="price" value="{{ old('price', $product->price) }}"
                               id="price"
                               class="form-control"
                               required
                        >
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/products/includes/result_messages.blade.php
@if($errors->any())
    <div class="row justify-content-center">
        <div class="col-md-11">
            <div class="alert alert-danger" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                <ul>
                    @foreach($errors->all() as $errorMsg)
                        <li>{{ $errorMsg }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endif

@if(session('success'))
    <div class="row justify-content-center">
        <div class="col-md-11">
            <div class="alert alert-success" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                {!! session()->get('success') !!}
            </div>
        </div>
    </div>
@endif

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">

                @include('products.includes.result_messages')

                <div class="card">
                    <div class="card-header">
                        <a class="btn btn-primary" href="{{ route('products.create') }}">Add</a>
                    </div>
                    <div class="card-body">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Price</th>
                                <th>Author</th>
                            </tr>
                            </thead>
                            <tbody>

                                @foreach($products as $product)
                                    <tr @if(Auth::id() == $product->user_id)
                                            style="background-color: #ccc;"
                                        @endif
                                        >
                                        <td>
                                            {{ $product->id }}
                                        </td>
                                        <td>
                                            <a href="{{ route('products.show', $product->id) }}">
                                                {{ $product->name }}
                                            </a>
                                        </td>
                                        <td>
                                            {{ $product->price }}
                                        </td>
                                        <td>
                                            {{ $product->author->name }}
                                        </td>
                                    </tr>
                                @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">

                @include('products.includes.result_messages')

                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-sm-10">
                                <h4>{{ $product->name }}</h4>
                            </div>
                            <div class="col-sm-1">

                                @can('update', $product)
                                    <a class="btn btn-primary" href="{{ route('products.edit', $product->id) }}">
                                        Edit
                                    </a>
                                @endcan

                            </div>
                            <div class="col-sm-1">

                                @can('delete', $product)
                                    <form id="delete-{{ $product->id }}" action="{{ route('products.destroy', $product->id) }}" method="POST">
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                @endcan

                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <ul>
                            <li>ID: {{ $product->id }}</li>
                            <li>Name: {{ $product->name }}</li>
                            <li>Price: {{ $product->price }}</li>
                            <li>Author: {{ $product->author->name }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection